import { createSlice } from "@reduxjs/toolkit";

const prodListSlice = createSlice({
	name: "prodList",
	initialState: {
		prods: [
			{
				id: 1,
				name: "Игровой ноутбук Acer Nitro 5 AN515-57-55P2 (NH.QESEP.00D)",
				image: [
					"../images/Nitro1.jpg",
					"../images/Nitro2.jpg",
					"../images/Nitro3.jpg",
					"../images/Nitro4.jpg",
					"../images/Nitro5.jpg",
					"../images/Nitro6.jpg",
				],
				price: 3199.0,
				sale: "",
				descript: [
					"Экран:",
					"15.6 1920x1080 px, IPS 144 Гц",
					"Процессор:",
					"Intel Core-i5 11400H 6 -ядерный, 2.7 ГГц - 4.5 ГГц, Tiger Lake",
					"Видеокарта:",
					"Дискретная NVIDIA GeForce RTX 3050 Ti 4 ГБ GDDR6",
					"Память:",
					"ОЗУ 8 ГБ DDR4 , SSD 512 ГБ",
				],
				type: "Игровой ноутбук",
				manufacturer: "Acer",
			},
			{
				id: 2,
				name: "Холодильник Samsung RB37A52N0B1/WT",
				image: [
					"../images/refrSamsung1.jpg",
					"../images/refrSamsung2.jpg",
					"../images/refrSamsung3.jpg",
					"../images/refrSamsung4.jpg",
					"../images/refrSamsung5.jpg",
					"../images/refrSamsung6.jpg",
				],
				price: 2388.0,
				sale: 2899.0,
				descript: [
					"No Frost:",
					"Полный",
					"Полезный объем: ",
					"367 л, 269 л + 98 л",
					"Цвет: ",
					"Черный",
					"Высота:",
					"201 см",
				],
				type: "Холодильник",
				manufacturer: "Samsung",
			},
			{
				id: 3,
				name: "Телевизор LG 50UQ75006LF",
				image: [
					"../images/LG1.jpg",
					"../images/LG2.jpg",
					"../images/LG3.jpg",
					"../images/LG4.jpg",
					"../images/LG5.jpg",
					"../images/LG6.jpg",
				],
				price: 1695.0,
				sale: 2035.0,
				descript: [
					"Smart TV:",
					"Да",
					"Тип экрана:",
					"LCD",
					"Диагональ:",
					"50 дюймов",
					"Разрешение: ",
					"Ultra HD 4K-3840x2160 пикс.",
				],
				type: "Телевизор",
				manufacturer: "LG",
			},
			{
				id: 4,
				name: "Пылесос SAMSUNG VS15T7031R1/EV",
				image: [
					"../images/vacuumSamsung1.jpg",
					"../images/vacuumSamsung2.jpg",
					"../images/vacuumSamsung3.jpg",
					"../images/vacuumSamsung4.jpg",
					"../images/vacuumSamsung5.jpg",
					"../images/vacuumSamsung6.jpg",
				],
				price: 975.0,
				sale: 1359.0,
				descript: [
					"Тип пылесоса:",
					"Вертикальный",
					"Тип уборки:",
					"Сухая",
					"Тип пылесборника: ",
					"Контейнер",
					"Потребляемая мощность:",
					"410 Вт",
				],
				type: "Пылесос",
				manufacturer: "SAMSUNG",
			},
			{
				id: 5,
				name: "Стиральная машина Samsung WW70A6S23AE/LP",
				image: [
					"../images/washingSumsung1.jpg",
					"../images/washingSumsung2.jpg",
					"../images/washingSumsung3.jpg",
					"../images/washingSumsung4.jpg",
					"../images/washingSumsung5.jpg",
					"../images/washingSumsung6.jpg",
				],
				price: 1560.0,
				sale: 1949.0,
				descript: [
					"Тип мотора:",
					"Инверторный",
					"Вес загрузки белья:",
					"7 кг",
					"Глубина:",
					"45 см",
					"Скорость отжима до:",
					"1200 об/мин",
				],
				type: "Стиральная машина",
				manufacturer: "Samsung",
			},
			{
				id: 6,
				name: "Микроволновая печь Samsung MG23K3513AS/BW",
				image: [
					"../images/mcwSamsung1.jpg",
					"../images/mcwSamsung2.jpg",
					"../images/mcwSamsung3.jpg",
					"../images/mcwSamsung4.jpg",
					"../images/mcwSamsung5.jpg",
					"../images/mcwSamsung6.jpg",
				],
				price: 445.0,
				sale: 509.0,
				descript: [
					"Исполнение:",
					"Отдельностоящая",
					"Тип:",
					"Микроволны (Соло), Гриль",
					"Объем микроволновой печи:",
					"23 л",
					"Внутреннее покрытие стенок:",
					"Биокерамика",
				],
				type: "Микроволновая печь",
				manufacturer: "Samsung",
			},
			{
				id: 7,
				name: "Кухонный комбайн Aresa AR-1706",
				image: [
					"../images/aresa1.jpg",
					"../images/aresa2.jpg",
					"../images/aresa3.jpg",
					"../images/aresa4.jpg",
					"../images/aresa5.jpg",
					"../images/aresa6.jpg",
				],
				price: 869.0,
				sale: 940.0,
				descript: [
					"Тип:",
					"Кухонный комбайн",
					"Мощность:",
					"150 Вт",
					"Количество скоростных режимов:",
					" 1",
					"Терка для драников:",
					"Да",
				],
				type: "Кухонный комбайн",
				manufacturer: "Aresa",
			},
			{
				id: 8,
				name: "Акустическая станция SVEN MS-2070",
				image: [
					"../images/acusticSven1.jpg",
					"../images/acusticSven2.jpg",
					"../images/acusticSven3.jpg",
					"../images/acusticSven4.jpg",
					"../images/acusticSven5.jpg",
					"../images/acusticSven6.jpg",
				],
				price: 279.0,
				sale: 319.0,
				descript: [
					"Дисплей:",
					"Да",
					"Акустическое исполнение:",
					"2.1",
					"Общая выходная мощность:",
					"60 Вт",
					"Интерфейсы и порты:",
					"USB, Bluetooth, Линейный аудиовход, Кардридер",
				],
				type: "Акустическая система",
				manufacturer: "SVEN",
			},
			{
				id: 9,
				name: "Фитнес-браслет Xiaomi Smart Band 7 Pro M2141B1 (черный) BHR5970GL5",
				image: [
					"../images/clock1.jpg",
					"../images/clock2.jpg",
					"../images/clock3.jpg",
					"../images/clock4.jpg",
					"../images/clock5.jpg",
					"../images/clock6.jpg",
				],
				price: 249.0,
				sale: "",
				descript: [
					"Экран:",
					"1.64 AMOLED",
					"Звонки:",
					"Управление",
					"Уведомления:",
					"Входящие вызовы, E-mail, Социальные сети, Данные о тренировке, Будильник, Календарь, SMS",
					"Защита от пыли и влаги:",
					"5 АТМ",
				],
				type: "вентилятор",
				manufacturer: "Sumsong",
			},
			{
				id: 10,
				name: "Кофемашина DeLonghi Dinamica Plus ECAM 370.95.S",
				image: [
					"../images/cofe1.jpg",
					"../images/cofe2.jpg",
					"../images/cofe3.jpg",
					"../images/cofe4.jpg",
					"../images/cofe5.jpg",
					"../images/cofe6.jpg",
				],
				price: 2899.0,
				sale: 3099.0,
				descript: [
					"Тип используемого кофе:",
					"В зернах, Молотый",
					"Мощность:",
					"1450 Вт",
					"Давление:",
					"19 бар",
					"Материал жерновов:",
					"Нержавеющая сталь",
				],
				type: "кофемашина",
				manufacturer: "DeLonghi",
			},
			{
				id: 11,
				name: "Мясорубка Aresa AR-2101",
				image: [
					"../images/meat1.jpg",
					"../images/meat2.jpg",
					"../images/meat3.jpg",
					"../images/meat4.jpg",
					"../images/meat5.jpg",
					"../images/meat6.jpg",
				],
				price: 206.0,
				sale: 228.0,
				descript: [
					"Максимальная мощность при блокировке вала:",
					"1700 Вт",
					"Реверс:",
					"Да",
					"Барабаны:",
					"Нет",
					"Насадка для домашней колбасы:",
					"Да",
				],
				type: "Мясорубка",
				manufacturer: "Aresa",
			},
			{
				id: 12,
				name: "Ноутбук Asus X515JA-EJ1814",
				image: [
					"../images/asus1.jpg",
					"../images/asus2.jpg",
					"../images/asus3.jpg",
					"../images/asus4.jpg",
					"../images/asus5.jpg",
					"../images/asus6.jpg",
				],
				price: 1475.0,
				sale: 1575.0,
				descript: [
					"Емкость SSD:",
					"256 ГБ",
					"Модель видеокарты:",
					"UHD Graphics",
					"Объем оперативной памяти:",
					"8 ГБ",
					"Модель процессора:",
					"6805",
				],
				type: "Ноутбук",
				manufacturer: "Asus",
			},
			{
				id: 13,
				name: "Умная колонка Яндекс Станция Макс (YNDX-0008) черный + пульт YNDX-00401",
				image: [
					"../images/yandex1.jpg",
					"../images/yandex2.jpg",
					"../images/yandex3.jpg",
					"../images/yandex4.jpg",
					"../images/yandex5.jpg",
					"../images/yandex6.jpg",
				],
				price: 999,
				sale: 1199,
				descript: [
					"Умная колонка:",
					"Да",
					"Акустическое исполнение:",
					"5.0",
					"Общая выходная мощность:",
					"65 Вт",
					"FM-радио:",
					"Да",
				],
				type: "Умная колонка",
				manufacturer: "Яндекс",
			},
			{
				id: 14,
				name: "Смартфон Xiaomi POCO M5 6GB/128GB (черный) EU",
				image: [
					"../images/miPoco1.jpg",
					"../images/miPoco2.jpg",
					"../images/miPoco3.jpg",
					"../images/miPoco4.jpg",
					"../images/miPoco5.jpg",
					"../images/miPoco6.jpg",
				],
				price: 619.0,
				sale: 719.0,
				descript: [
					"Экран:",
					" 6.58 1080x2408 пикселей, IPS",
					"Процессор:",
					"MediaTek Helio G99 2.2 ГГц",
					"Память:",
					"ОЗУ 6 ГБ , 128 ГБ",
					"Количество мегапикселей камеры:",
					"50 Мп",
				],
				type: "Смартфон",
				manufacturer: "Xiaomi",
			},
		],
	},
	reducers: {
		addProd(state, actions) {
			state.prods = [...state.prods, actions.payload];
		},
		removeProd(state, actions) {
			state.prods = state.prods.filter((prod) => prod.id !== actions.payload);
		},
	},
});

export default prodListSlice.reducer;
export const { addProd, removeProd } = prodListSlice.actions;
