import { createSlice } from "@reduxjs/toolkit";

const prodListSlice = createSlice({
	name: "prodList",
	initialState: {
		prods: [
			{
				id: 1,
				image: [
					"../images/Nitro1.jpg",
					"../images/Nitro2.jpg",
					"../images/Nitro3.jpg",
					"../images/Nitro4.jpg",
					"../images/Nitro5.jpg",
					"../images/Nitro6.jpg",
				],
				price: 567,
				sale: "",
				type: "монитор",
				manufacturer: "Sumsong",
				name: "Монитор Sumsong 27B1H",
			},
			{
				id: 2,
				image: [
					"../images/refrSamsung1.jpg",
					"../images/refrSamsung2.jpg",
					"../images/refrSamsung3.jpg",
					"../images/refrSamsung4.jpg",
					"../images/refrSamsung5.jpg",
					"../images/refrSamsung6.jpg",
				],
				price: 426,
				sale: 479,
				type: "монитор",
				manufacturer: "GL",
				name: "Монитор GL 24B2H",
			},
			{
				id: 3,
				image: [
					"../images/LG1.jpg",
					"../images/LG2.jpg",
					"../images/LG3.jpg",
					"../images/LG4.jpg",
					"../images/LG5.jpg",
					"../images/LG6.jpg",
				],
				price: 928,
				sale: 1054,
				type: "монитор",
				manufacturer: "Pholips",
				name: "Монитор Pholips G32V",
			},
			{
				id: 4,
				image: [
					"../images/vacuumSamsung1.jpg",
					"../images/vacuumSamsung2.jpg",
					"../images/vacuumSamsung3.jpg",
					"../images/vacuumSamsung4.jpg",
					"../images/vacuumSamsung5.jpg",
					"../images/vacuumSamsung6.jpg",
				],
				price: 432,
				sale: 322,
				type: "монитор",
				manufacturer: "Mo",
				name: "Монитор Mo 24BBQ",
			},
			{
				id: 5,
				image: [
					"../images/washingSumsung1.jpg",
					"../images/washingSumsung2.jpg",
					"../images/washingSumsung3.jpg",
					"../images/washingSumsung4.jpg",
					"../images/washingSumsung5.jpg",
					"../images/washingSumsung6.jpg",
				],
				price: 232,
				sale: 322,
				type: "холодильник",
				manufacturer: "Pholips",
				name: "Холодильник Олимп",
			},
			{
				id: 6,
				image: [
					"../images/mcwSamsung1.jpg",
					"../images/mcwSamsung2.jpg",
					"../images/mcwSamsung3.jpg",
					"../images/mcwSamsung4.jpg",
					"../images/mcwSamsung5.jpg",
					"../images/mcwSamsung6.jpg",
				],
				price: 233,
				sale: 322,
				type: "холодильник",
				manufacturer: "Sumsong",
				name: "Холодильник Sumsong",
			},
			{
				id: 7,
				image: [
					"../images/aresa1.jpg",
					"../images/aresa2.jpg",
					"../images/aresa3.jpg",
					"../images/aresa4.jpg",
					"../images/aresa5.jpg",
					"../images/aresa6.jpg",
				],
				price: 234,
				sale: 322,
				type: "холодильник",
				manufacturer: "Mo",
				name: "Холодильник Mo",
			},
			{
				id: 8,
				image: [
					"../images/acusticSven1.jpg",
					"../images/acusticSven2.jpg",
					"../images/acusticSven3.jpg",
					"../images/acusticSven4.jpg",
					"../images/acusticSven5.jpg",
					"../images/acusticSven6.jpg",
				],
				price: 235,
				sale: 322,
				type: "холодильник",
				manufacturer: "GL",
				name: "Холодильник GL",
			},
			{
				id: 9,
				image: [
					"../images/clock1.jpg",
					"../images/clock2.jpg",
					"../images/clock3.jpg",
					"../images/clock4.jpg",
					"../images/clock5.jpg",
					"../images/clock6.jpg",
				],
				price: 236,
				sale: 322,
				type: "вентилятор",
				manufacturer: "Sumsong",
				name: "Вентилятор Sumsong Osos1104",
			},
			{
				id: 10,
				image: [
					"../images/cofe1.jpg",
					"../images/cofe2.jpg",
					"../images/cofe3.jpg",
					"../images/cofe4.jpg",
					"../images/cofe5.jpg",
					"../images/cofe6.jpg",
				],
				price: 237,
				sale: 322,
				type: "вентилятор",
				manufacturer: "GL",
				name: "Вентилятор GL V5000",
			},
			{
				id: 11,
				image: [
					"../images/meat1.jpg",
					"../images/meat2.jpg",
					"../images/meat3.jpg",
					"../images/meat4.jpg",
					"../images/meat5.jpg",
					"../images/meat6.jpg",
				],
				price: 238,
				sale: 322,
				type: "вентилятор",
				manufacturer: "Pholips",
				name: "Вентилятор Pholips  Hurricane3000",
			},
			{
				id: 12,
				image: [
					"../images/asus1.jpg",
					"../images/asus2.jpg",
					"../images/asus3.jpg",
					"../images/asus4.jpg",
					"../images/asus5.jpg",
					"../images/asus6.jpg",
				],
				price: 239,
				sale: 322,
				type: "вентилятор",
				manufacturer: "Mo",
				name: "Вентилятор Mo HomeWind 1S",
			},
			{
				id: 13,
				image: [
					"../images/yandex1.jpg",
					"../images/yandex2.jpg",
					"../images/yandex3.jpg",
					"../images/yandex4.jpg",
					"../images/yandex5.jpg",
					"../images/yandex6.jpg",
				],
				price: 240,
				sale: 322,
				type: "телевизор",
				manufacturer: "Sumsong",
				name: "Телевизор Sumsong",
			},
			{
				id: 14,
				image: [
					"../images/miPoco1.jpg",
					"../images/miPoco2.jpg",
					"../images/miPoco3.jpg",
					"../images/miPoco4.jpg",
					"../images/miPoco5.jpg",
					"../images/miPoco6.jpg",
				],
				price: 241,
				sale: 322,
				type: "телевизор",
				manufacturer: "GL",
				name: "Телевизор GL",
			},
		],
	},
	reducers: {
		addProd(state, actions) {
			state.prods = [...state.prods, actions.payload];
		},
		removeProd(state, actions) {
			state.prods = state.prods.filter((prod) => prod.id !== actions.payload);
		},
	},
});

export default prodListSlice.reducer;
export const { addProd, removeProd } = prodListSlice.actions;
